# Generated by Django 5.2.7 on 2025-10-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='providers', to='app1.servicecategory'),
        ),
    ]
